SELECT Id, Company, Name, Affinity_Cold__c, Phone, Email, PostalCode, Status, Suspended_Closed_Reason__c, SIC2007_Code__c, SIC2007_Description__c, SIC2007_Code2__c, SIC2007_Description2__c, SIC2007_Code3__c, SIC2007_Description3__c
FROM Salesforce..Lead
WHERE OwnerId not in ('00GD0000003UVlRMAW','005D00000037SsAIAU') and
(
PostalCode like 'LE%' or
PostalCode like 'PE%' or
PostalCode like 'NR%' or
PostalCode like 'DY%' or
PostalCode like 'B1%' or
PostalCode like 'B2%' or
PostalCode like 'B3%' or
PostalCode like 'B4%' or
PostalCode like 'B5%' or
PostalCode like 'B6%' or
PostalCode like 'B7%' or
PostalCode like 'B8%' or
PostalCode like 'B9%' or
PostalCode like 'CV%' or
PostalCode like 'NN%' or
PostalCode like 'CB%' or
PostalCode like 'IP%' or
PostalCode like 'HR%' or
PostalCode like 'WR%' or
PostalCode like 'OX%' or
PostalCode like 'MK%' or
PostalCode like 'SG%' or
PostalCode like 'NP%' or
PostalCode like 'GL%' or
PostalCode like 'CF%' or
PostalCode like 'HP%' or
PostalCode like 'LU%' or
PostalCode like 'AL%' or
PostalCode like 'CM%' or
PostalCode like 'CO%' or
PostalCode like 'BS%' or
PostalCode like 'SN%' or
PostalCode like 'RG%' or
PostalCode like 'SL%' or
PostalCode like 'SS%' or
PostalCode like 'ME%' or
PostalCode like 'CT%' or
PostalCode like 'TA%' or
PostalCode like 'BA%' or
PostalCode like 'SP%' or
PostalCode like 'SO%' or
PostalCode like 'GU%' or
PostalCode like 'RH%' or
PostalCode like 'TN%' or
PostalCode like 'EX%' or
PostalCode like 'TQ%' or
PostalCode like 'DT%' or
PostalCode like 'BH%' or
PostalCode like 'PO%' or
PostalCode like 'BN%' or
PostalCode like 'WD%' or
PostalCode like 'EN%' or
PostalCode like 'HA%' or
PostalCode like 'UB%' or
PostalCode like 'TW%' or
PostalCode like 'KT%' or
PostalCode like 'CR%' or
PostalCode like 'BR%' or
PostalCode like 'DA%' or
PostalCode like 'IG%' or
PostalCode like 'RM%' or
PostalCode like 'N1%' or
PostalCode like 'N2%' or
PostalCode like 'N3%' or
PostalCode like 'N4%' or
PostalCode like 'N5%' or
PostalCode like 'N6%' or
PostalCode like 'N7%' or
PostalCode like 'N8%' or
PostalCode like 'N9%' or
PostalCode like 'NW%' or
PostalCode like 'W1%' or
PostalCode like 'W2%' or
PostalCode like 'W3%' or
PostalCode like 'W4%' or
PostalCode like 'W5%' or
PostalCode like 'W6%' or
PostalCode like 'W7%' or
PostalCode like 'W8%' or
PostalCode like 'W9%' or
PostalCode like 'SW%' or
PostalCode like 'SE%' or
PostalCode like 'WC%' or
PostalCode like 'EC%' or
PostalCode like 'N1%' or
PostalCode like 'N2%' or
PostalCode like 'N3%' or
PostalCode like 'N4%' or
PostalCode like 'N5%' or
PostalCode like 'N6%' or
PostalCode like 'N7%' or
PostalCode like 'N8%' or
PostalCode like 'N9%'
)