--SELECT 'or [respondent(s)] like '+CHAR(39)+'%'+Company+'%'+CHAR(39)
--FROM SalesforceReporting..BadCompanies

SELECT *
FROM SalesforceReporting..CourtServe
WHERE
[respondent(s)] like '%CSC%'
or [respondent(s)] like '%Skechers%'
or [respondent(s)] like '%Toast%'
or [respondent(s)] like '%Progressive Recruitment%'
or [respondent(s)] like '%Progressive Recruitment Ltd%'
or [respondent(s)] like '%Fire Station%'
or [respondent(s)] like '%Jobcentre%'
or [respondent(s)] like '%The National Trust%'
or [respondent(s)] like '%Persimmon Homes Ltd%'
or [respondent(s)] like '%Tradeteam%'
or [respondent(s)] like '%HMP Exter%'
or [respondent(s)] like '%The Perfume Shop%'
or [respondent(s)] like '%Belfour Beattie%'
or [respondent(s)] like '%Volvo%'
or [respondent(s)] like '%Asda%'
or [respondent(s)] like '%HM Prison Services%'
or [respondent(s)] like '%Fire Service%'
or [respondent(s)] like '%Chanel%'
or [respondent(s)] like '%Sofaworks%'
or [respondent(s)] like '%BP%'
or [respondent(s)] like '%Tesco%'
or [respondent(s)] like '%Nails Inc%'
or [respondent(s)] like '%Argos%'
or [respondent(s)] like '%P H Jones%'
or [respondent(s)] like '%PH Jones%'
or [respondent(s)] like '%Tui Travel%'
or [respondent(s)] like '%Youth Offending Services%'
or [respondent(s)] like '%Smyths Toys%'
or [respondent(s)] like '%Harveys Furniture%'
or [respondent(s)] like '%Irish Tourist Board%'
or [respondent(s)] like '%Fire Brigade%'
or [respondent(s)] like '%Cash Converters%'
or [respondent(s)] like '%Poundstretcher%'
or [respondent(s)] like '%Pound stretcher%'
or [respondent(s)] like '%G B S T%'
or [respondent(s)] like '%BP Oil UK Ltd%'
or [respondent(s)] like '%Rowlands Ltd%'
or [respondent(s)] like '%Farmfoods%'
or [respondent(s)] like '%C S C%'
or [respondent(s)] like '%Kurt Geiger%'
or [respondent(s)] like '%Willmott Dixon Group%'
or [respondent(s)] like '%Willmott Dixon Interiors%'
or [respondent(s)] like '%Ben Sherman%'
or [respondent(s)] like '%Hoopers%'
or [respondent(s)] like '%Fossil%'
or [respondent(s)] like '%Mulberry%'
or [respondent(s)] like '%B & M Retail%'
or [respondent(s)] like '%Criminal Justice Service%'
or [respondent(s)] like '%Booze Buster%'
or [respondent(s)] like '%Nottingham Building Society%'
or [respondent(s)] like '%Care Quality Commission%'
or [respondent(s)] like '%32 Signal Regiment%'
or [respondent(s)] like '%501 Squadron%'
or [respondent(s)] like '%51 Signal Squadron%'
or [respondent(s)] like '%606 Squadron%'
or [respondent(s)] like '%Accor%'
or [respondent(s)] like '%Age UK%'
or [respondent(s)] like '%Alamo%'
or [respondent(s)] like '%Aldi Stores Ltd%'
or [respondent(s)] like '%All Saints%'
or [respondent(s)] like '%American Golf Ltd%'
or [respondent(s)] like '%Apple%'
or [respondent(s)] like '%Apple Store%'
or [respondent(s)] like '%Armani Exchange%'
or [respondent(s)] like '%Ask%'
or [respondent(s)] like '%Audi%'
or [respondent(s)] like '%Audi Finance%'
or [respondent(s)] like '%Auto Trader%'
or [respondent(s)] like '%Autoglass%'
or [respondent(s)] like '%Avis Rent A Car%'
or [respondent(s)] like '%Axa%'
or [respondent(s)] like '%Bangladesh High Commission%'
or [respondent(s)] like '%Barnardos%'
or [respondent(s)] like '%Beatties%'
or [respondent(s)] like '%Bedfordshire Police%'
or [respondent(s)] like '%Beefeater%'
or [respondent(s)] like '%Best Western%'
or [respondent(s)] like '%Blue Inc%'
or [respondent(s)] like '%Booker Cash and Carry%'
or [respondent(s)] like '%Bose%'
or [respondent(s)] like '%BP Oil%'
or [respondent(s)] like '%Britannia Hotel%'
or [respondent(s)] like '%British Army%'
or [respondent(s)] like '%BT Mail Centre%'
or [respondent(s)] like '%C S L %'
or [respondent(s)] like '%Caffe Nero Group%'
or [respondent(s)] like '%Carpet Direct Ltd%'
or [respondent(s)] like '%Cartridge Works%'
or [respondent(s)] like '%Central Scotland Police%'
or [respondent(s)] like '%Choice%'
or [respondent(s)] like '%Citibank%'
or [respondent(s)] like '%Citizens Advice Bureau%'
or [respondent(s)] like '%Clintons%'
or [respondent(s)] like '%Connexions%'
or [respondent(s)] like '%Copthorne%'
or [respondent(s)] like '%Coroners Office%'
or [respondent(s)] like '%Costa Coffee%'
or [respondent(s)] like '%Crowne%'
or [respondent(s)] like '%Currys%'
or [respondent(s)] like '%Dagenham Motors Plc%'
or [respondent(s)] like '%Days Inn%'
or [respondent(s)] like '%De vere%'
or [respondent(s)] like '%DHL Supply Chain%'
or [respondent(s)] like '%Dixon Group%'
or [respondent(s)] like '%Doubletree by Hilton%'
or [respondent(s)] like '%Doubletree  %'
or [respondent(s)] like '%Dr Martens%'
or [respondent(s)] like '%Dunelm Mill%'
or [respondent(s)] like '%East of England Ambulance%'
or [respondent(s)] like '%Edwardian%'
or [respondent(s)] like '%Ernest Jones%'
or [respondent(s)] like '%Essex County Fire and Rescue%'
or [respondent(s)] like '%Euro Car%'
or [respondent(s)] like '%Europcar%'
or [respondent(s)] like '%Europe%'
or [respondent(s)] like '%Evans Halshaw%'
or [respondent(s)] like '%Evolution%'
or [respondent(s)] like '%Fire and Rescue Service%'
or [respondent(s)] like '%Fitness First%'
or [respondent(s)] like '%Foot Locker%'
or [respondent(s)] like '%Footasylum%'
or [respondent(s)] like '%Forest Freight Ltd%'
or [respondent(s)] like '%Four seasons%'
or [respondent(s)] like '%GAP%'
or [respondent(s)] like '%H M Coastguard%'
or [respondent(s)] like '%Halford plc%'
or [respondent(s)] like '%Hays Specialist Recruitment%'
or [respondent(s)] like '%Headmasters%'
or [respondent(s)] like '%Health and Safety Executive%'
or [respondent(s)] like '%Heaven V%'
or [respondent(s)] like '%Herbal Life%'
or [respondent(s)] like '%Hilton%'
or [respondent(s)] like '%HM Revenue and Customs%'
or [respondent(s)] like '%Holiday inn%'
or [respondent(s)] like '%Holland and Barrett%'
or [respondent(s)] like '%Homebase%'
or [respondent(s)] like '%Homebase & Co%'
or [respondent(s)] like '%Hotel Ibis%'
or [respondent(s)] like '%House of Fraser%'
or [respondent(s)] like '%Howdens Joinery Company%'
or [respondent(s)] like '%Humberside Probation Services%'
or [respondent(s)] like '%Ibis%'
or [respondent(s)] like '%Ibis Hotel%'
or [respondent(s)] like '%Inchcape Volkswagen%'
or [respondent(s)] like '%Intercontinental%'
or [respondent(s)] like '%Jewson%'
or [respondent(s)] like '%Jewson%'
or [respondent(s)] like '%Job Centre Plus%'
or [respondent(s)] like '%John Lewis%'
or [respondent(s)] like '%K F C%'
or [respondent(s)] like '%KFC%'
or [respondent(s)] like '%Kwik Fit%'
or [respondent(s)] like '%Le Meridian%'
or [respondent(s)] like '%Learn Direct%'
or [respondent(s)] like '%Leiths%'
or [respondent(s)] like '%Lex Autolease%'
or [respondent(s)] like '%Lexus %'
or [respondent(s)] like '%Lexus Leicester Sales%'
or [respondent(s)] like '%Living Room%'
or [respondent(s)] like '%Lush%'
or [respondent(s)] like '%Lx%'
or [respondent(s)] like '%Mac%'
or [respondent(s)] like '%Macdonald%'
or [respondent(s)] like '%Machine Mart%'
or [respondent(s)] like '%Malmaison%'
or [respondent(s)] like '%Manpower%'
or [respondent(s)] like '%Maplin Electronics Ltd%'
or [respondent(s)] like '%Marriott Hotel%'
or [respondent(s)] like '%Marriott Leisure%'
or [respondent(s)] like '%Marstons Brewery%'
or [respondent(s)] like '%Member of Scottish Parliament%'
or [respondent(s)] like '%Mencap%'
or [respondent(s)] like '%Mentor%'
or [respondent(s)] like '%Mercure%'
or [respondent(s)] like '%Midland Hotel%'
or [respondent(s)] like '%Ministry of Defence%'
or [respondent(s)] like '%MP%'
or [respondent(s)] like '%N H S%'
or [respondent(s)] like '%Nandos%'
or [respondent(s)] like '%National Archives of Scotland%'
or [respondent(s)] like '%National Tyres  & Autocare%'
or [respondent(s)] like '%National Windscreens%'
or [respondent(s)] like '%Nationwide Bank%'
or [respondent(s)] like '%Neighbourhood Watch%'
or [respondent(s)] like '%Network Rail%'
or [respondent(s)] like '%Next Home Store%'
or [respondent(s)] like '%Next  %'
or [respondent(s)] like '%NHS%'
or [respondent(s)] like '%Novotel%'
or [respondent(s)] like '%Nu Interiors Northern Ltd%'
or [respondent(s)] like '%o2%'
or [respondent(s)] like '%Odeon Cinemas Ltd%'
or [respondent(s)] like '%P C World%'
or [respondent(s)] like '%Park Inn%'
or [respondent(s)] like '%Park Inn Northampton%'
or [respondent(s)] like '%PC World%'
or [respondent(s)] like '%PC World%'
or [respondent(s)] like '%Perrys%'
or [respondent(s)] like '%Pizza Express%'
or [respondent(s)] like '%Police%'
or [respondent(s)] like '%Post Office%'
or [respondent(s)] like '%Premier Inn%'
or [respondent(s)] like '%Pret A Manger%'
or [respondent(s)] like '%Procurator Fiscal%'
or [respondent(s)] like '%Professional Music Technology%'
or [respondent(s)] like '%Q Hotels %'
or [respondent(s)] like '%Radisson%'
or [respondent(s)] like '%RAF%'
or [respondent(s)] like '%Ralph Lauren%'
or [respondent(s)] like '%Ramada%'
or [respondent(s)] like '%Ree Specialist Recruitment%'
or [respondent(s)] like '%Reed Employment PLC%'
or [respondent(s)] like '%Relate%'
or [respondent(s)] like '%Renaissance%'
or [respondent(s)] like '%Revolution%'
or [respondent(s)] like '%Royal Air Force Careers%'
or [respondent(s)] like '%Royal Mail Group Ltd%'
or [respondent(s)] like '%Royal Navy Headquarters%'
or [respondent(s)] like '%RSM International Ltd%'
or [respondent(s)] like '%RSPCA%'
or [respondent(s)] like '%SAGA%'
or [respondent(s)] like '%Sainsburys Local%'
or [respondent(s)] like '%Scotts Quaker Oats Ltd%'
or [respondent(s)] like '%SEAT UK%'
or [respondent(s)] like '%Secom PLC%'
or [respondent(s)] like '%Securitas%'
or [respondent(s)] like '%Smarts%'
or [respondent(s)] like '%Social Services%'
or [respondent(s)] like '%Sommerfields%'
or [respondent(s)] like '%South Glocestershire%'
or [respondent(s)] like '%South Lanarkshire Council%'
or [respondent(s)] like '%Stagecoach%'
or [respondent(s)] like '%Staples%'
or [respondent(s)] like '%Starbuck Coffee Company UK Limited%'
or [respondent(s)] like '%Starbucks%'
or [respondent(s)] like '%Starbucks Coffee Company%'
or [respondent(s)] like '%Stratchclyde Police%'
or [respondent(s)] like '%Subway%'
or [respondent(s)] like '%Superdry%'
or [respondent(s)] like '%Suzuki%'
or [respondent(s)] like '%T Mobile%'
or [respondent(s)] like '%Tarmac Ltd%'
or [respondent(s)] like '%Territorial Army%'
or [respondent(s)] like '%Tesco Express%'
or [respondent(s)] like '%The Body Shop%'
or [respondent(s)] like '%The Co-operative Food%'
or [respondent(s)] like '%The Living Room%'
or [respondent(s)] like '%The Money Shop%'
or [respondent(s)] like '%The Princes Trust%'
or [respondent(s)] like '%The Royal Mail%'
or [respondent(s)] like '%Thistle%'
or [respondent(s)] like '%Topps Tiles PLC%'
or [respondent(s)] like '%Total Catering Equipment%'
or [respondent(s)] like '%Town Council%'
or [respondent(s)] like '%Trader Media%'
or [respondent(s)] like '%Travel Inn%'
or [respondent(s)] like '%Travelodge%'
or [respondent(s)] like '%Urban Outfitters%'
or [respondent(s)] like '%Vantage Toyota%'
or [respondent(s)] like '%Vauxhall Spares Centre%'
or [respondent(s)] like '%Victim Support%'
or [respondent(s)] like '%Virgin Media%'
or [respondent(s)] like '%West Lothian Council%'
or [respondent(s)] like '%Wetherspoons%'
or [respondent(s)] like '%WH Smiths%'
or [respondent(s)] like '%WH Smiths News%'
or [respondent(s)] like '%Wickes%'
or [respondent(s)] like '%Your Move%'
or [respondent(s)] like '%Cash Express%'
or [respondent(s)] like '%Commonwealth Parliamentary Association%'
or [respondent(s)] like '%Radley & Co%'
or [respondent(s)] like '%Fire Safety Legislation%'
or [respondent(s)] like '%EE%'
or [respondent(s)] like '%Budget Rental Car%'
or [respondent(s)] like '%Esporta%'
or [respondent(s)] like '%Nike UK Ltd%'
or [respondent(s)] like '%Ugg Australia%'
or [respondent(s)] like '%The Financial Services Compensation Scheme%'
or [respondent(s)] like '%Eurospar%'
or [respondent(s)] like '%Northern Rail%'
or [respondent(s)] like '%Grimsby Crown Court%'
or [respondent(s)] like '%Direct Golf UK Ltd%'
or [respondent(s)] like '%Co Operative%'
or [respondent(s)] like '%HSBC%'
or [respondent(s)] like '%Bridgefords%'
or [respondent(s)] like '%Co Op%'
or [respondent(s)] like '%British Heart Foundation%'
or [respondent(s)] like '%NHS Trust%'
or [respondent(s)] like '%Village Vets%'
or [respondent(s)] like '%British Red Cross%'
or [respondent(s)] like '%Royal Air Force%'
or [respondent(s)] like '%Rymans%'
or [respondent(s)] like '%Hollister%'
or [respondent(s)] like '%British Telecom%'
or [respondent(s)] like '%Enterprise Rent-A-Car%'
or [respondent(s)] like '%Air Ambulance%'
or [respondent(s)] like '%B P Oil%'
or [respondent(s)] like '%Balfour Beatty%'
or [respondent(s)] like '%Birds Eye%'
or [respondent(s)] like '%chidline%'
or [respondent(s)] like '%cineworld%'
or [respondent(s)] like '%cisco systems%'
or [respondent(s)] like '%county council%'
or [respondent(s)] like '%county court%'
or [respondent(s)] like '%E E%'
or [respondent(s)] like '%immigration office%'
or [respondent(s)] like '%indesit Ltd UK%'
or [respondent(s)] like '%Metropolitan Council%'
or [respondent(s)] like '%Lafarge Cement%'
or [respondent(s)] like '%Leonard Cheshire Foundation%'
or [respondent(s)] like '%London Zoo%'
or [respondent(s)] like '%Magistrates Court%'
or [respondent(s)] like '%Mecedes Benz%'
or [respondent(s)] like '%Mercedes Benz%'
or [respondent(s)] like '%Morrisons Pharmacy%'
or [respondent(s)] like '%National Car Park Plc%'
or [respondent(s)] like '%Optimax Laser Eye Clinic%'
or [respondent(s)] like '%Orient Express%'
or [respondent(s)] like '%Plumb Centre%'
or [respondent(s)] like '%building society%'
or [respondent(s)] like '%Provident%'
or [respondent(s)] like '%Probation Trust%'
or [respondent(s)] like '%Pure Gym%'
or [respondent(s)] like '%R N I B%'
or [respondent(s)] like '%Shell%'
or [respondent(s)] like '%Solicitors%'
or [respondent(s)] like '%The Co-operative Travel%'
or [respondent(s)] like '%The Virgin Cosmetics Company%'
or [respondent(s)] like '%Timberland%'
or [respondent(s)] like '%Towergate%'
or [respondent(s)] like '%Unison%'
or [respondent(s)] like '%World Duty Free Ltd%'
or [respondent(s)] like '%B P%'
or [respondent(s)] like '%NSPCC%'
or [respondent(s)] like '%N S P C C%'
or [respondent(s)] like '%RSPCA%'
or [respondent(s)] like '%R S P C A%'
or [respondent(s)] like '%T Mobile%'
or [respondent(s)] like '%Texaco%'
or [respondent(s)] like '%Halfords%'
or [respondent(s)] like '%Kwik-Fit%'
or [respondent(s)] like '%Go Outdoors%'
or [respondent(s)] like '%Harveys%'
or [respondent(s)] like '%Savills%'
or [respondent(s)] like '%Nissan%'
or [respondent(s)] like '%Standard Life%'
or [respondent(s)] like '%Swinton%'
or [respondent(s)] like '%Oxfam%'
or [respondent(s)] like '%Wilkinsons%'
or [respondent(s)] like '%Wilkos%'
or [respondent(s)] like '%Wilkinsons%'
or [respondent(s)] like '%Wilkos%'
or [respondent(s)] like '%Ryman%'
or [respondent(s)] like '%The Body Shop%'
or [respondent(s)] like '%Bargain Booze%'
or [respondent(s)] like '%Plumb Center%'
or [respondent(s)] like '%BBC%'
or [respondent(s)] like '%EON%'
or [respondent(s)] like '%Royal Mail%'
or [respondent(s)] like '%Heart FM%'
or [respondent(s)] like '%ATS euromaster Ltd%'
or [respondent(s)] like '%Arnold Clark%'
or [respondent(s)] like '%L A Fitness%'
or [respondent(s)] like '%LA Fitness%'
or [respondent(s)] like '%The Salvation Army%'
or [respondent(s)] like '%BUPA%'
or [respondent(s)] like '%Hamptons International Sales%'
or [respondent(s)] like '%Palmer Snell%'
or [respondent(s)] like '%Dulux%'
or [respondent(s)] like '%Reeds Rains%'
or [respondent(s)] like '%Wilco Motosave Ltd%'
or [respondent(s)] like '%Satair%'
or [respondent(s)] like '%Regus%'
or [respondent(s)] like '%David Lloyd%'
or [respondent(s)] like '%Bridgfords%'
or [respondent(s)] like '%Virgin Active%'
or [respondent(s)] like '%W F Electrical%'
or [respondent(s)] like '%Plumbase%'
or [respondent(s)] like '%Allied Healthcare Group%'
or [respondent(s)] like '%Hamptons International%'
or [respondent(s)] like '%National Car Parks%'
or [respondent(s)] like '%Comedy Central%'
or [respondent(s)] like '%Comedy Central%'
or [respondent(s)] like '%Ginsters%'
or [respondent(s)] like '%Bannatynes%'
or [respondent(s)] like '%Service Point%'
or [respondent(s)] like '%Integral%'
or [respondent(s)] like '%O C S%'
or [respondent(s)] like '%Reel Cinema%'
or [respondent(s)] like '%Savience Group%'
or [respondent(s)] like '%Regis Internationl Ltd%'
or [respondent(s)] like '%Co-operative funeralcare%'
or [respondent(s)] like '%Co-operative funeralcare%'
or [respondent(s)] like '%Co-operative funeralcare%'
or [respondent(s)] like '%Dixons%'
or [respondent(s)] like '%Stanley Black and Decker%'
or [respondent(s)] like '%stratstone%'
or [respondent(s)] like '%Barnard Marcus%'
or [respondent(s)] like '%Santander%'
or [respondent(s)] like '%Bristol Street Motors%'
or [respondent(s)] like '%E-On%'
or [respondent(s)] like '%B P%'
or [respondent(s)] like '%csl Sofas%'
or [respondent(s)] like '%D W Sports%'
or [respondent(s)] like '%Build a Bear workshop%'
or [respondent(s)] like '%Evan Halshaw%'
or [respondent(s)] like '%Menzies%'
or [respondent(s)] like '%Pets at Home Ltd%'
or [respondent(s)] like '%W M Morrison Supermarkets PLC%'
or [respondent(s)] like '%W M Morrison Supermarkets PLC%'
or [respondent(s)] like '%Bosch%'
or [respondent(s)] like '%Bosch%'
or [respondent(s)] like '%Volvo%'
or [respondent(s)] like '%Dorothy Perkins%'
or [respondent(s)] like '%Salvation Army%'
or [respondent(s)] like '%Tie Rack%'
or [respondent(s)] like '%Mecca Bingo%'
or [respondent(s)] like '%currys digital%'
or [respondent(s)] like '%Ambulance Services%'
or [respondent(s)] like '%Auto Windscreens Ltd%'
or [respondent(s)] like '%Shuropody%'
or [respondent(s)] like '%Max Spielmann%'
or [respondent(s)] like '%Euro Car Parts%'
or [respondent(s)] like '%National Blood Service%'
or [respondent(s)] like '%Moss Bros%'
or [respondent(s)] like '%Sellwood%'
or [respondent(s)] like '%Magnet%'
or [respondent(s)] like '%Howdens Joinery%'
or [respondent(s)] like '%Bensons for Beds%'
or [respondent(s)] like '%Lacie%'
or [respondent(s)] like '%Keyline Builders Merchants%'
or [respondent(s)] like '%semi-chem%'
or [respondent(s)] like '%Haart%'
or [respondent(s)] like '%Caffe Nero%'
or [respondent(s)] like '%Supercuts%'
or [respondent(s)] like '%Toni & Guy%'
or [respondent(s)] like '%Capita%'
or [respondent(s)] like '%Greenthumb%'
or [respondent(s)] like '%Acteon%'
or [respondent(s)] like '%Benchmarx Kitchen & Joinery%'
or [respondent(s)] like '%Heron Foods%'
or [respondent(s)] like '%Heron Frozen Foods%'
or [respondent(s)] like '%Abbotts%'
or [respondent(s)] like '%Alan de Maid%'
or [respondent(s)] like '%Forest Bureau%'
or [respondent(s)] like '%Frank Innes%'
or [respondent(s)] like '%Freeman Forman%'
or [respondent(s)] like '%Fulfords Estate Agents%'
or [respondent(s)] like '%Geering & Colyer%'
or [respondent(s)] like '%Hetheringtons%'
or [respondent(s)] like '%John D Wood & Co%'
or [respondent(s)] like '%King & Chasemore%'
or [respondent(s)] like '%Miller Countrywide%'
or [respondent(s)] like '%Morris Dibben%'
or [respondent(s)] like '%Palmer Snell%'
or [respondent(s)] like '%RA Bennett & Partners%'
or [respondent(s)] like '%Spencers Countrywide%'
or [respondent(s)] like '%Stratton Creber%'
or [respondent(s)] like '%Taylors Estate Agents%'
or [respondent(s)] like '%Watson Bull & Porter%'
or [respondent(s)] like '%Wilson Peacock%'
or [respondent(s)] like '%Mann%'
or [respondent(s)] like '%PMS%'
or [respondent(s)] like '%PayMobil%'
or [respondent(s)] like '%PlayMobil%'
or [respondent(s)] like '%Hallmark%'
or [respondent(s)] like '%TK MAXX%'
or [respondent(s)] like '%Homesense%'
or [respondent(s)] like '%Bannatyne%'
or [respondent(s)] like '%A A%'
or [respondent(s)] like '%Camden Motors%'
or [respondent(s)] like '%One Stop%'
or [respondent(s)] like '%paperchase%'
or [respondent(s)] like '%Cemetery%'
or [respondent(s)] like '%Breezes%'
or [respondent(s)] like '%Playboy TV%'
or [respondent(s)] like '%Shopmobility%'
or [respondent(s)] like '%Green thumb%'
or [respondent(s)] like '%Parts Center%'
or [respondent(s)] like '%Central Auto Suppleis%'
or [respondent(s)] like '%Central Auto Supplies%'
or [respondent(s)] like '%Asphaltic Roofing Supplies%'
or [respondent(s)] like '%One-Stop%'
or [respondent(s)] like '%Molton Brown%'
or [respondent(s)] like '%Scope%'
or [respondent(s)] like '%B.U.P.A.%'
or [respondent(s)] like '%Thomas Cook Travel%'
or [respondent(s)] like '%Spec savers%'
or [respondent(s)] like '%Contraceptive Services%'
or [respondent(s)] like '%The Entertainer%'
or [respondent(s)] like '%A Plant%'
or [respondent(s)] like '%Salon Services%'
or [respondent(s)] like '%Sue Ryder Care%'
or [respondent(s)] like '%Patel House Furnishings%'
or [respondent(s)] like '%Rentokil%'
or [respondent(s)] like '%H Samuel%'
or [respondent(s)] like '%Wilkinson%'
or [respondent(s)] like '%Hanson Concrete%'
or [respondent(s)] like '%Wyevale Garden Centre%'
or [respondent(s)] like '%Thomson%'
or [respondent(s)] like '%D W Sports Fitness%'
or [respondent(s)] like '%Cambian Group%'
or [respondent(s)] like '%Whitworth Chemists%'
or [respondent(s)] like '%Immigration Advice Service%'
or [respondent(s)] like '%Oasis Dental Care Ltd%'
or [respondent(s)] like '%Brandon Tool Hire%'
or [respondent(s)] like '%Wine Rack%'
or [respondent(s)] like '%Crown Court%'
or [respondent(s)] like '%Tyneside Council%'
or [respondent(s)] like '%Catholic Church%'
or [respondent(s)] like '%Shaw Trust%'
or [respondent(s)] like '%National Autistic Society%'
or [respondent(s)] like '%C R U S E Bereavement Care%'
or [respondent(s)] like '%P D S A%'
or [respondent(s)] like '%Age (UK)%'
or [respondent(s)] like '%Links of London ltd%'
or [respondent(s)] like '%Batleys%'
or [respondent(s)] like '%Carpetright%'
or [respondent(s)] like '%BHS%'
or [respondent(s)] like '%B H S%'
or [respondent(s)] like '%McDonalds%'
or [respondent(s)] like '%Rownlands Pharmacy%'
or [respondent(s)] like '%Menkind%'
or [respondent(s)] like '%National Trust%'
or [respondent(s)] like '%Avon%'
or [respondent(s)] like '%GAP Kids%'
or [respondent(s)] like '%G A P Kids%'
or [respondent(s)] like '%Dunnes%'
or [respondent(s)] like '%Lindsay & Gilmour%'
or [respondent(s)] like '%ASDA supermarket%'
or [respondent(s)] like '%Barclays%'
or [respondent(s)] like '%Interlink Express Parcels Ltd%'
or [respondent(s)] like '%The Disney Store%'
or [respondent(s)] like '%Chiquitos%'
or [respondent(s)] like '%Wagamamas%'
or [respondent(s)] like '%Wagamama%'
or [respondent(s)] like '%Hugo Boss%'
or [respondent(s)] like '%Lorne Stewart Plc%'
or [respondent(s)] like '%TNT%'
or [respondent(s)] like '%T N T%'
or [respondent(s)] like '%Claires Accessories%'
or [respondent(s)] like '%Real Life Options%'
or [respondent(s)] like '%Stepping Stones for Families%'
or [respondent(s)] like '%UK Mail%'
or [respondent(s)] like '%The Flight Centre%'
or [respondent(s)] like '%Co-Operative Group%'
or [respondent(s)] like '%DynoRod%'
or [respondent(s)] like '%Companion Care Vets%'
or [respondent(s)] like '%Jacksons Building Centres%'
or [respondent(s)] like '%Hotel Chocolat%'
or [respondent(s)] like '%Bottega Veneta%'
or [respondent(s)] like '%Heart 103%'
or [respondent(s)] like '%Save the Children%'
or [respondent(s)] like '%Concentrix%'
or [respondent(s)] like '%DW Fitness%'
or [respondent(s)] like '%Fire & Rescue%'
or [respondent(s)] like '%Coffee Republic%'
or [respondent(s)] like '%London Borough of Camden%'
or [respondent(s)] like '%LUnited Synagogue%'
or [respondent(s)] like '%Winkworth Estate Agents%'
or [respondent(s)] like '%Unipart Automotive%'
or [respondent(s)] like '%UK Studies%'
or [respondent(s)] like '%Molly Maids%'
or [respondent(s)] like '%The Gap%'
or [respondent(s)] like '%Hi Q%'
or [respondent(s)] like '%Top Shop%'
or [respondent(s)] like '%Top Man%'
or [respondent(s)] like '%Barnardo%'
or [respondent(s)] like '%Spar%'
or [respondent(s)] like '%co-operative%'
or [respondent(s)] like '%Iceland%'
or [respondent(s)] like '%Gala Bingo%'
or [respondent(s)] like '%Tommy Hilfiger%'
or [respondent(s)] like '%Pizza Hut%'
or [respondent(s)] like '%Women%Royal Voluntary Service%'
or [respondent(s)] like '%WRVS%'
or [respondent(s)] like '%Motor Parts Direct%'
or [respondent(s)] like '%Nuffield Health%'
or [respondent(s)] like '%Gascogine Pees%'
or [respondent(s)] like '%Direct Golf UK%'
or [respondent(s)] like '%Truckforce Ltd%'
or [respondent(s)] like '%William H Brown%'
or [respondent(s)] like '%Jackson Stops%'
or [respondent(s)] like '%BMW%'
or [respondent(s)] like '%Everwell%'
or [respondent(s)] like '%B Bowden & Co Ltd%'
or [respondent(s)] like '%Womens Aid%'
or [respondent(s)] like '%The Royal British Legion%'
or [respondent(s)] like '%Specsavers%'
or [respondent(s)] like '%The Hospice Shop%'
or [respondent(s)] like '%Salford City Council%'
or [respondent(s)] like '%Konica Minolta Business Solutions UK Ltd%'
or [respondent(s)] like '%Kenmal Technology College%'
or [respondent(s)] like '%I T V%'
or [respondent(s)] like '%G4S%'
or [respondent(s)] like '%G4%'
or [respondent(s)] like '%Balfour Beattie%'
or [respondent(s)] like '%Arriva%'
or [respondent(s)] like '%Sports Direct%'
or [respondent(s)] like '%Bright House%'
or [respondent(s)] like '%Superdrug%'
or [respondent(s)] like '%Knight Frank LLP%'
or [respondent(s)] like '%Cancer Research UK%'
or [respondent(s)] like '%German Swedish & French Car Parts%'
or [respondent(s)] like '%Morelli%'
or [respondent(s)] like '%Quick Stop Shop%'
or [respondent(s)] like '%WH Smith%'
or [respondent(s)] like '%D F D S%'
or [respondent(s)] like '%Richer Sounds%'
or [respondent(s)] like '%Prime Life Ltd%'
or [respondent(s)] like '%PrimeLife%'
or [respondent(s)] like '%Safer Neighbourhoods%'
or [respondent(s)] like '%Sixt Rent a Car%'
or [respondent(s)] like '%Ricoh UK Ltd%'
or [respondent(s)] like '%Moss & Leakey Opticians%'
or [respondent(s)] like '%St. johns Ambulance%'
or [respondent(s)] like '%Gardnr & Scardifield%'
or [respondent(s)] like '%Gardner & Scardifield%'
or [respondent(s)] like '%BodyCare%'
or [respondent(s)] like '%B & Q%'
or [respondent(s)] like '%DHL%'
or [respondent(s)] like '%Plumbing Trade Supplies%'
or [respondent(s)] like '%Travis Perkins%'
or [respondent(s)] like '%Lloyds TSB%'
or [respondent(s)] like '%Rowlands Pharmacy%'
or [respondent(s)] like '%Sainsburys Pharmacy%'
or [respondent(s)] like '%Boots%'
or [respondent(s)] like '%Cash Generators%'
or [respondent(s)] like '%Screwfix%'
or [respondent(s)] like '%Righton Ltd%'
or [respondent(s)] like '%Sexual Health%'
or [respondent(s)] like '%Wilmott Dixon%'
or [respondent(s)] like '%Burberry%'
or [respondent(s)] like '%Barchester%'
or [respondent(s)] like '%Just Car Clinics%'
or [respondent(s)] like '%Concep%'
or [respondent(s)] like '%Harbour Commissioners%'
or [respondent(s)] like '%Douglas Allen%'
or [respondent(s)] like '%Buffer Bear Nursery%'
or [respondent(s)] like '%WM Morrison%'
or [respondent(s)] like '%Biz Space%'
or [respondent(s)] like '%Douglas & Gordon%'
or [respondent(s)] like '%Guy Salmon%'
or [respondent(s)] like '%Graham Plumbing & Heating%'
or [respondent(s)] like '%Regis%'
or [respondent(s)] like '%Norbert dentressangle%'
or [respondent(s)] like '%Pre School Learning Alliance%'
or [respondent(s)] like '%Booker Cash & Carry%'
or [respondent(s)] like '%Kinleigh Folkard & Hayward%'
or [respondent(s)] like '%City Plumbing Supplies%'
or [respondent(s)] like '%Wickes Building Supplies%'
or [respondent(s)] like '%Livingwell Health Club%'
or [respondent(s)] like '%Makro%'
or [respondent(s)] like '%Places for People%'
or [respondent(s)] like '%Foxtons%'
or [respondent(s)] like '%Ranstad%'
or [respondent(s)] like '%BB Coffee and Muffins%'
or [respondent(s)] like '%Fed Ex%'
or [respondent(s)] like '%Accord Lets%'
or [respondent(s)] like '%Alder King%'
or [respondent(s)] like '%Andrew Butler%'
or [respondent(s)] like '%Andrew Reeves%'
or [respondent(s)] like '%Ashton Kurkinshaw%'
or [respondent(s)] like '%Austin & Wyatt%'
or [respondent(s)] like '%Bairstow Eves%'
or [respondent(s)] like '%Beresford Adams%'
or [respondent(s)] like '%Blundells%'
or [respondent(s)] like '%Carson & Co%'
or [respondent(s)] like '%Chappell & Matthews%'
or [respondent(s)] like '%Churchill Lettings%'
or [respondent(s)] like '%Country Waterside%'
or [respondent(s)] like '%Cryers%'
or [respondent(s)] like '%Dixons Estate Agents%'
or [respondent(s)] like '%Entwistle Green%'
or [respondent(s)] like '%Faron Sutaria%'
or [respondent(s)] like '%Border Force%'
or [respondent(s)] like '%William Wilson%'
or [respondent(s)] like '%Mouchel%'
or [respondent(s)] like '%K H Hair%'
or [respondent(s)] like '%Bell Decorating Group%'
or [respondent(s)] like '%Pipe Center%'
or [respondent(s)] like '%Beesley & Fildes%'
or [respondent(s)] like '%Evander%'
or [respondent(s)] like '%Lloyds%'
or [respondent(s)] like '%Harringtons%'
or [respondent(s)] like '%Harringtons Salon%'
or [respondent(s)] like '%Formula One Autocentres%'
or [respondent(s)] like '%Mobility Furniture%'
or [respondent(s)] like '%Selco%'
or [respondent(s)] like '%Huws Gray Building Materials Centre%'
or [respondent(s)] like '%Procam%'
or [respondent(s)] like '%Homeserve%'
or [respondent(s)] like '%Witness Service%'
or [respondent(s)] like '%Univar UK Ltd%'
or [respondent(s)] like '%Crabtree & Evelyn%'
or [respondent(s)] like '%Gibbs & Dandy plc%'
or [respondent(s)] like '%Shred It%'
or [respondent(s)] like '%A C A S%'
or [respondent(s)] like '%Kier%'
or [respondent(s)] like '%Listers%'
or [respondent(s)] like '%Jollyes Petfood Superstore%'
or [respondent(s)] like '%Nationwide Crash Repair Centres Ltd%'
or [respondent(s)] like '%Job Centre%'
or [respondent(s)] like '%Lookers plc%'
or [respondent(s)] like '%Costco%'
or [respondent(s)] like '%Booker Wholesale%'
or [respondent(s)] like '%Chesterton Humberts%'
or [respondent(s)] like '%Lodnon Borough%'
or [respondent(s)] like '%Majestic Wine Warehouse%'
or [respondent(s)] like '%European Metals Recycling%'
or [respondent(s)] like '%Ward & Partners%'
or [respondent(s)] like '%Bluebird Care%'
or [respondent(s)] like '%Porsche%'
or [respondent(s)] like '%Visit Scotland%'
or [respondent(s)] like '%Kip McGrath Education Centres%'
or [respondent(s)] like '%Turnbull & Co%'
or [respondent(s)] like '%Scout Group%'
or [respondent(s)] like '%Explore Learning%'
or [respondent(s)] like '%Jenkins%'
or [respondent(s)] like '%Co operative funeralcare%'
or [respondent(s)] like '%Everest Ltd%'
or [respondent(s)] like '%H L Hutchinson Ltd%'
or [respondent(s)] like '%Jones Lang Lasalle%'
or [respondent(s)] like '%Rush Salons%'
or [respondent(s)] like '%Signs Express%'
or [respondent(s)] like '%Graham The Plumbers Merchant%'
or [respondent(s)] like '%BT Fleet%'
or [respondent(s)] like '%D I Y - S O S Ltd%'
or [respondent(s)] like '%Jordan Fishwick%'
or [respondent(s)] like '%Leightons Opticians%'
or [respondent(s)] like '%Karro Food Groups%'
or [respondent(s)] like '%St Annes Community Service%'
or [respondent(s)] like '%Borders%'
or [respondent(s)] like '%Borders Police%'
or [respondent(s)] like '%Johnsons the Cleaners%'
or [respondent(s)] like '%Autobar%'
or [respondent(s)] like '%Abel%'
or [respondent(s)] like '%Abel Alarms%'
or [respondent(s)] like '%Abel Alarm%'
or [respondent(s)] like '%Thrifty Care & Van Rental%'
or [respondent(s)] like '%Lafarge Readymix%'
or [respondent(s)] like '%H M V%'
or [respondent(s)] like '%Frenco%'
or [respondent(s)] like '%Wimpy%'
or [respondent(s)] like '%Co operative society%'
or [respondent(s)] like '%Robert Dyas Ltd%'
or [respondent(s)] like '%Six Physio%'
or [respondent(s)] like '%Edrington Distillers%'
or [respondent(s)] like '%cooperative society%'
or [respondent(s)] like '%Kerry Foods Ltd%'
or [respondent(s)] like '%Worldwide Laser Eye Company%'
or [respondent(s)] like '%Opitcal Express%'
or [respondent(s)] like '%B U P A%'
or [respondent(s)] like '%Thomson Cook Travel%'
or [respondent(s)] like '%Action for Children%'
or [respondent(s)] like '%Basler%'
or [respondent(s)] like '%Store Twenty One%'
or [respondent(s)] like '%Alliance Disposables%'
or [respondent(s)] like '%Portakabin%'
or [respondent(s)] like '%Home Farm Trust%'
or [respondent(s)] like '%Askham Bryant College%'
or [respondent(s)] like '%Askham Bryan College%'
or [respondent(s)] like '%Alpha Plus School%'
or [respondent(s)] like '%Wyvale%'
or [respondent(s)] like '%HMV%'
or [respondent(s)] like '%D H L%'
or [respondent(s)] like '%Roger Bullivant Ltd%'
or [respondent(s)] like '%Probation Services%'
or [respondent(s)] like '%Vehicle & Operator Service Agency%'
or [respondent(s)] like '%Patient Advice & Liaison Service%'
or [respondent(s)] like '%Europcar UK Ltd%'
or [respondent(s)] like '%Haines Watts%'
or [respondent(s)] like '%Hertz UK Ltd%'
or [respondent(s)] like '%The Y Advice & Support Centre%'
or [respondent(s)] like '%Whittard of Chelsea%'
or [respondent(s)] like '%C C F Ltd%'
or [respondent(s)] like '%Vision Call%'
or [respondent(s)] like '%Talk Talk%'
or [respondent(s)] like '%Busy Bees%'
or [respondent(s)] like '%Orders of St John Care Trust%'
or [respondent(s)] like '%Turning Point%'
or [respondent(s)] like '%Gaucho%'
or [respondent(s)] like '%Central Tyre Ltd%'
or [respondent(s)] like '%Parish Council%'
or [respondent(s)] like '%Rape & Sexual Abuse Counselling%'
or [respondent(s)] like '%Blue Cross%'
or [respondent(s)] like '%barbour%'
or [respondent(s)] like '%Battersea Dogs and Cats Home%'
or [respondent(s)] like '%Sister of Nazareth%'
or [respondent(s)] like '%brighthouse%'
or [respondent(s)] like '%Loomis%'
or [respondent(s)] like '%Chubb%'
or [respondent(s)] like '%Wildlife Trust%'
or [respondent(s)] like '%Natural England%'
or [respondent(s)] like '%Prison Department%'
or [respondent(s)] like '%Childrens Schools & Families%'
or [respondent(s)] like '%Children Schools & Families%'
or [respondent(s)] like '%H M P%'
or [respondent(s)] like '%Cats Protection%'
or [respondent(s)] like '%Eden Supported Living%'
or [respondent(s)] like '%Pfizer%'
or [respondent(s)] like '%Mamas & Papas%'
or [respondent(s)] like '%Future Care Homes Ltd%'
or [respondent(s)] like '%Henri-Lloyd Ltd%'
or [respondent(s)] like '%R N L I%'
or [respondent(s)] like '%RNLI%'
or [respondent(s)] like '%Primecare%'
or [respondent(s)] like '%Warren James Jewellers Ltd%'
or [respondent(s)] like '%Integrated Youth Support%'
or [respondent(s)] like '%The Kidnergartens%'
or [respondent(s)] like '%Flower Show%'
or [respondent(s)] like '%Leslie Davis%'
or [respondent(s)] like '%Tims & Parker Ltd%'
or [respondent(s)] like '%Alamo Rent A Car (UK) Ltd%'
or [respondent(s)] like '%Budgens%'
or [respondent(s)] like '%Sport Stat%'
or [respondent(s)] like '%Sportradar%'
or [respondent(s)] like '%Bablake Wines Ltd%'
or [respondent(s)] like '%Leap%'
or [respondent(s)] like '%Rentakill%'
or [respondent(s)] like '%Beaverbrooks%'
or [respondent(s)] like '%Lafarge%'
or [respondent(s)] like '%Travelpharm%'
or [respondent(s)] like '%Ernst & Young LLP%'
or [respondent(s)] like '%Jack Wills%'
or [respondent(s)] like '%Trade Union Congress%'
or [respondent(s)] like '%Marriotts%'
or [respondent(s)] like '%Headlines%'
or [respondent(s)] like '%Ted Baker%'
or [respondent(s)] like '%JD Wetherspoon%'
or [respondent(s)] like '%B B C%'
or [respondent(s)] like '%GoodYear%'
or [respondent(s)] like '%Hilton Hotel%'
or [respondent(s)] like '%Hilton Hotels%'
or [respondent(s)] like '%ATS Euromaster%'
or [respondent(s)] like '%Marie Curie Cancer Care%'
or [respondent(s)] like '%UKStudy.com%'
or [respondent(s)] like '%Thomsons%'
or [respondent(s)] like '%Eat%'
or [respondent(s)] like '%River Island%'
or [respondent(s)] like '%XL Vets%'
or [respondent(s)] like '%Christies%'
or [respondent(s)] like '%Corning Ltd%'
or [respondent(s)] like '%BAM%'
or [respondent(s)] like '%Carphone Warehouse%'
or [respondent(s)] like '%Yo Sushi%'
or [respondent(s)] like '%UKIP%'
or [respondent(s)] like '%U K I P%'
or [respondent(s)] like '%H B Fuller%'
or [respondent(s)] like '%Premier Travel Inn%'
or [respondent(s)] like '%Good Year%'
or [respondent(s)] like '%F Hinds Jewellers%'
or [respondent(s)] like '%City Hall%'
or [respondent(s)] like '%Door 21%'
or [respondent(s)] like '%Q S%'