INSERT INTO
SalesforceReporting..HS_Activity2
(
	  [Consultant]
      ,[RunDate]
      ,[NormalWorkingDays]
      ,[PhysicalDays]
      ,[FirstVisits]
      ,[InstallVisits]
      ,[AnnualVisits]
      ,[ExtraContractual]
      ,[OtherExtraVisits]
      ,[AddiServices]
      ,[ArrCancelled]
      ,[DayCancelled]
      ,[TotalClientVisits]
      ,[AverageVisits]
      ,[AdminDays]
      ,[Sickness]
      ,[Helpline]
      ,[CallsTaken]
      ,[OtherMeetings]
      ,[Holidays]
      ,[NotOnboarded]
      ,[NotMigrated]
      ,[NewSystemsOS]
      ,[ReportsOS]
      ,[ClientSite1]
      ,[Date1]
      ,[Reason1]
      ,[ClientSite2]
      ,[Date2]
      ,[Reason2]
      ,[ClientSite3]
      ,[Date3]
      ,[Reason3]
      ,[ClientSite4]
      ,[Date4]
      ,[Reason4]
      ,[ServiceIssues1]
      ,[ServiceIssues2]
      ,[ServiceIssues3]
      ,[ServiceIssues4]
      ,[OtherIssues1]
      ,[OtherIssues2]
      ,[OtherIssues3]
      ,[OtherIssues4]
      ,[RefSystemsOS]
      )

SELECT 
MAX(Consultant) Consultant, 
MAX(dateadd(d,CONVERT(int, RunDate),'1899-12-30')) RunDate,
SUM(NormalWorkingDays) NormalWorkingDays,
SUM(PhysicalDays) PhysicalDays,
SUM(FirstVisits) FirstVisits,
SUM(InstallVisits) InstallVisits,
SUM(AnnualVisits) AnnualVisits,
SUM(ExtraContractual) ExtraContractual,
SUM(OtherExtraVisits) OtherExtraVisits,
SUM(AddiServices) AddiServices,
SUM(ArrCancelled) ArrCancelled,
SUM(DayCancelled) DayCancelled,
SUM(TotalClientVisits) TotalClientVisits,
SUM(AverageVisits) AverageVisits,
SUM(AdminDays) AdminDays,
SUM(Sickness) Sickness,
SUM(Helpline) Helpline,
SUM(CallsTaken) CallsTaken,
SUM(OtherMeetings) OtherMeetings,
SUM(Holidays) Holidays,
SUM(NotOnboarded) NotOnboarded,
SUM(NotMigrated) NotMigrated,
SUM(NewSystemsOS) NewSystemsOS,
SUM(ReportsOS) ReportsOS,
MAX(ClientSite1) ClientSite1,
MAX(Date1) Date1,
MAX(Reason1) Reason1,
MAX(ClientSite2) ClientSite2,
MAX(Date2) Date2,
MAX(Reason2) Reason2,
MAX(ClientSite3) ClientSite3,
MAX(Date3) Date3,
MAX(Reason3) Reason3,
MAX(ClientSite4) ClientSite4,
MAX(Date4) Date4,
MAX(Reason4) Reason4,
MAX(ServiceIssues1) ServiceIssues1,
MAX(ServiceIssues2) ServiceIssues2,
MAX(ServiceIssues3) ServiceIssues3,
MAX(ServiceIssues4) ServiceIssues4,
MAX(OtherIssues1) OtherIssues1,
MAX(OtherIssues2) OtherIssues2,
MAX(OtherIssues3) OtherIssues3,
MAX(OtherIssues4) OtherIssues4,
SUM(RefSystemsOS) RefSystemsOS

FROM
(
	SELECT 
	1 Id, 
	F3 Consultant, 
	'' RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS
	FROM
	(
	SELECT F3, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 1
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	F2 RunDate,
	CONVERT(decimal(18,1),F4) NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 3
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	CONVERT(decimal(18,1),F4) PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 4
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	CONVERT(decimal(18,1),F2) FirstVisits,
	CONVERT(decimal(18,1),F4) InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 7
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	CONVERT(decimal(18,1),F2) AnnualVisits,
	CONVERT(decimal(18,1),F4) ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 9
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	CONVERT(decimal(18,1),F2) OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 11
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	CONVERT(decimal(18,1),F2) AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 13
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	CONVERT(decimal(18,1),F2) ArrCancelled,
	CONVERT(decimal(18,1),F4) DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 15
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	CONVERT(decimal(18,1),F2) TotalClientVisits,
	CONVERT(decimal(18,1),F4) AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 17
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	CONVERT(decimal(18,1),F2) AdminDays,
	CONVERT(decimal(18,1),F4) Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 20
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	CONVERT(decimal(18,1),F2) Helpline,
	CONVERT(decimal(18,1),F4) CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 22
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	CONVERT(decimal(18,1),F2) OtherMeetings,
	CONVERT(decimal(18,1),F4) Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 24
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	CONVERT(decimal(18,1),F2) NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 27
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	CONVERT(decimal(18,1),F2) NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 29
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	CONVERT(decimal(18,1),F2) NewSystemsOS,
	CONVERT(decimal(18,1),F4) ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F2, F4, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 32
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	CONVERT(decimal(18,1),F2) RefSystemsOS 
	FROM
	(
	SELECT F2, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 34
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	F1 ClientSite1,
	F2 Date1,
	F3 Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, F2, F3, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 37
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	F1 ClientSite2,
	F2 Date2,
	F3 Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, F2, F3, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 38
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	F1 ClientSite3,
	F2 Date3,
	F3 Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, F2, F3, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 39
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	F1 ClientSite4,
	F2 Date4,
	F3 Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, F2, F3, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 40
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	F1 ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 43
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	F1 ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 44
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	F1 ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 45
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	F1 ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 46
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	F1 OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 49
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	F1 OtherIssues2,
	'' OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 50
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	F1 OtherIssues3,
	'' OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 51
		UNION
	SELECT 
	1 Id, 
	'' Consultant, 
	0 RunDate,
	0 NormalWorkingDays,
	0 PhysicalDays,
	0 FirstVisits,
	0 InstallVisits,
	0 AnnualVisits,
	0 ExtraContractual,
	0 OtherExtraVisits,
	0 AddiServices,
	0 ArrCancelled,
	0 DayCancelled,
	0 TotalClientVisits,
	0 AverageVisits,
	0 AdminDays,
	0 Sickness,
	0 Helpline,
	0 CallsTaken,
	0 OtherMeetings,
	0 Holidays,
	0 NotOnboarded,
	0 NotMigrated,
	0 NewSystemsOS,
	0 ReportsOS,
	'' ClientSite1,
	'' Date1,
	'' Reason1,
	'' ClientSite2,
	'' Date2,
	'' Reason2,
	'' ClientSite3,
	'' Date3,
	'' Reason3,
	'' ClientSite4,
	'' Date4,
	'' Reason4,
	'' ServiceIssues1,
	'' ServiceIssues2,
	'' ServiceIssues3,
	'' ServiceIssues4,
	'' OtherIssues1,
	'' OtherIssues2,
	'' OtherIssues3,
	F1 OtherIssues4,
	0 RefSystemsOS 
	FROM
	(
	SELECT F1, ROW_NUMBER() OVER (ORDER BY ID) rn
	FROM SalesforceReporting..HS_Staging
	) detail
	WHERE rn = 52
) detail
GROUP BY Id

SELECT *
FROM SalesforceReporting..HS_Staging