IF OBJECT_ID('tempdb..#Noms') IS NOT NULL
	BEGIN
		DROP TABLE #Noms
	END

SELECT
MMSCIT004ContractID,
NLAccountID,
SUM(CONVERT(decimal(18,2),Debit)) TotalNominalDebit,
SUM(CONVERT(decimal(18,2),Credit)) TotalNominalCredit,
SUM(CONVERT(decimal(18,2),Debit))-SUM(CONVERT(decimal(18,2), Credit)) DebitMinusCredit
INTO
#Noms
FROM
CitationQMSLive..MMSCIT004Revenue qms
inner join CitationQMSLive..QMSContracts c ON qms.Narrative = c.ContractNo
GROUP BY
MMSCIT004ContractID,
NLAccountID

SELECT 
ctc.CustomerID,
ctc.MMSCIT004ContractID,
ctc.ContractNo,
ctc.SFDCContractNumber,
ctc.Signed,
ctc.IsIndexed,
ctc.Duration,
ctc.Value,
ctc.Deleted,
ctc.InvoiceDueDate,
ctc.OrdersCreated,
ctr1.NLAccountID,
ctc.Split1,
nl1.AccountNumber,
nl1.AccountCostCentre,
nl1.AccountName,
ctr1.TotalNominalDebit TotalNominal1Debit,
ctr1.TotalNominalCredit TotalNominal1Credit,
ctr1.DebitMinusCredit DebitMinusCredit,
ctr2.NLAccountID,
ctc.Split2,
nl2.AccountNumber,
nl2.AccountCostCentre,
nl2.AccountName,
ctr2.TotalNominalDebit TotalNominal2Debit,
ctr2.TotalNominalCredit TotalNominal2Credit,
ctr2.DebitMinusCredit DebitMinusCredit2,
ctc.BillingPattern_A,
ctc.BillingPattern_C,
ctc.MMSCIT004TemplateID,
ctt.ServiceType,
ctt.Name,
ctt.Year1Period1,
ctt.Year1Period2,
ctt.Year1Period3,
ctt.Year1Period4,
ctt.Year1Period5,
ctt.Year1Period6,
ctt.Year1Period7,
ctt.Year1Period8,
ctt.Year1Period9,
ctt.Year1Period10,
ctt.Year1Period11,
ctt.Year1Period12,
ctt.Year2Period1,
ctt.Year2Period2,
ctt.Year2Period3,
ctt.Year2Period4,
ctt.Year2Period5,
ctt.Year2Period6,
ctt.Year2Period7,
ctt.Year2Period8,
ctt.Year2Period9,
ctt.Year2Period10,
ctt.Year2Period11,
ctt.Year2Period12,
ctt.Year3Period1,
ctt.Year3Period2,
ctt.Year3Period3,
ctt.Year3Period4,
ctt.Year3Period5,
ctt.Year3Period6,
ctt.Year3Period7,
ctt.Year3Period8,
ctt.Year3Period9,
ctt.Year3Period10,
ctt.Year3Period11,
ctt.Year3Period12,
ctt.Year4Period1,
ctt.Year4Period2,
ctt.Year4Period3,
ctt.Year4Period4,
ctt.Year4Period5,
ctt.Year4Period6,
ctt.Year4Period7,
ctt.Year4Period8,
ctt.Year4Period9,
ctt.Year4Period10,
ctt.Year4Period11,
ctt.Year4Period12,
ctt.Year5Period1,
ctt.Year5Period2,
ctt.Year5Period3,
ctt.Year5Period4,
ctt.Year5Period5,
ctt.Year5Period6,
ctt.Year5Period7,
ctt.Year5Period8,
ctt.Year5Period9,
ctt.Year5Period10,
ctt.Year5Period11,
ctt.Year5Period12,
ctt.Year6Period1,
ctt.Year6Period2,
ctt.Year6Period3,
ctt.Year6Period4,
ctt.Year6Period5,
ctt.Year6Period6,
ctt.Year6Period7,
ctt.Year6Period8,
ctt.Year6Period9,
ctt.Year6Period10,
ctt.Year6Period11,
ctt.Year6Period12,
ctt.Year7Period1,
ctt.Year7Period2,
ctt.Year7Period3,
ctt.Year7Period4,
ctt.Year7Period5,
ctt.Year7Period6,
ctt.Year7Period7,
ctt.Year7Period8,
ctt.Year7Period9,
ctt.Year7Period10,
ctt.Year7Period11,
ctt.Year7Period12,
ctt.Year8Period1,
ctt.Year8Period2,
ctt.Year8Period3,
ctt.Year8Period4,
ctt.Year8Period5,
ctt.Year8Period6,
ctt.Year8Period7,
ctt.Year8Period8,
ctt.Year8Period9,
ctt.Year8Period10,
ctt.Year8Period11,
ctt.Year8Period12,
ctt.Year9Period1,
ctt.Year9Period2,
ctt.Year9Period3,
ctt.Year9Period4,
ctt.Year9Period5,
ctt.Year9Period6,
ctt.Year9Period7,
ctt.Year9Period8,
ctt.Year9Period9,
ctt.Year9Period10,
ctt.Year9Period11,
ctt.Year9Period12,
ctt.Year10Period1,
ctt.Year10Period2,
ctt.Year10Period3,
ctt.Year10Period4,
ctt.Year10Period5,
ctt.Year10Period6,
ctt.Year10Period7,
ctt.Year10Period8,
ctt.Year10Period9,
ctt.Year10Period10,
ctt.Year10Period11,
ctt.Year10Period12,
ctt.Year11Period1,
ctt.Year11Period2,
ctt.Year11Period3,
ctt.Year11Period4,
ctt.Year11Period5,
ctt.Year11Period6,
ctt.Year11Period7,
ctt.Year11Period8,
ctt.Year11Period9,
ctt.Year11Period10,
ctt.Year11Period11,
ctt.Year11Period12,
ctt.Year12Period1,
ctt.Year12Period2,
ctt.Year12Period3,
ctt.Year12Period4,
ctt.Year12Period5,
ctt.Year12Period6,
ctt.Year12Period7,
ctt.Year12Period8,
ctt.Year12Period9,
ctt.Year12Period10,
ctt.Year12Period11,
ctt.Year12Period12
FROM CitationQMSLive..MMSCIT004Contract ctc
left outer join CitationQMSLive..QMSContracts c ON ctc.ContractNo = c.ContractNo
left outer join CitationQMSLive..MMSCIT004Template ctt ON ctc.MMSCIT004TemplateID = ctt.TemplateID
left outer join #Noms ctr1 ON ctc.NLRevenue1ID = ctr1.NLAccountID and ctc.MMSCIT004ContractID = ctr1.MMSCIT004ContractID
left outer join #Noms ctr2 ON ctc.NLRevenue2ID = ctr2.NLAccountID and ctc.MMSCIT004ContractID = ctr2.MMSCIT004ContractID
left outer join CitationQMSLive..NLNominalAccount nl1 ON ctr1.NLAccountID = nl1.NLNominalAccountID and ctc.MMSCIT004ContractID = ctr1.MMSCIT004ContractID
left outer join CitationQMSLive..NLNominalAccount nl2 ON ctr2.NLAccountID = nl2.NLNominalAccountID and ctc.MMSCIT004ContractID = ctr2.MMSCIT004ContractID
WHERE c.ContractNo is not null