ALTER TABLE LeadChangeReview..Lead_SnapShots_May2018 ADD List_Type__c nvarchar(1300)

ALTER INDEX ALL ON LeadChangeReview..Lead_SnapShots_May2018 REBUILD

UPDATE LeadChangeReview..Lead_SnapShots_May2018
SET List_Type__c = 
case when CitationSector__c in ('ARCHITECTURAL & ENGINEERING','CARE','MANUFACTURING') then 'List 1a'
when CitationSector__c in ('CONSTRUCTION','DAY NURESERY','GLASS & GLAZING','GOLF CLUBS','SPORTS & ENTERTAINMENT','TRANSPORATION AND STORAGE',
'WATER SUPPLY ACTIVITIES') then 'List 1b'
when CitationSector__c in ('ACCOMMODATION','AGRICULTURE','CLEANING','FINANCIAL AND INSURANCE ACTIVITIES','FOOD & BEVERAGE','HUMAN HEALTH ACTIVITIES',
'MOTORTRADE','PHARMACY','RENTING & LEASING','SECURITY','VETERINARY ACTIVITIES','WHOLESALE EXCLUDING MOTOR') then 'List 2'
when CitationSector__c in ('ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES','B2C SERVICES','FUNERAL SERVICES','HORTICULTURE',
'INFORMATION AND COMMUNICATION','OTHER','PROFESSIONAL ACTIVITIES','REAL ESTATE ACTIVITIES','RETAIL EXCLUDING MOTOR') then 'List 3' end