SELECT ROW_NUMBER () OVER (PARTITION BY 1 ORDER BY DateStamp, companyName) Id
	  ,case when [DateStamp] <> '' then DATEADD(day, CONVERT(int, [DateStamp]), '1899-12-31')-1 else NULL end [DateStamp]
	  ,CONVERT(int, [ShorthornId]) [ShorthornId]
      ,[Sage Code]
      ,[companyName]
      ,CONVERT(int, [dealLength]) [dealLength]
      ,[Consultant Fullname]
      ,[title]
      ,[fullname]
      ,[email]
      ,CONVERT(int, [siteID]) [siteID]
      ,[postcode]
      ,[genTel]
      ,[genEmail]
      ,case when [signDate] <> '' then DATEADD(day, CONVERT(int, [signDate]), '1899-12-31')-1 else NULL end [signDate]
      ,case when [renewDate] <> '' then DATEADD(day, CONVERT(int, [renewDate]), '1899-12-31')-1 else NULL end [renewDate]
      ,case when [BookedAction] <> '' then DATEADD(day, CONVERT(int, [BookedAction]), '1899-12-31')-1 else NULL end [BookedAction]
      ,[Call Type]
      ,CONVERT(decimal(18,2), [DealValue]) [DealValue]
      ,[Sector]
      ,[SalesforceId]
      ,[Segment]
      ,CONVERT(int, [ContactID])[ContactID]
      ,[dealStatus]
      ,case when [Last Time Additional Visit] <> '' then DATEADD(day, CONVERT(int, [Last Time Additional Visit]), '1899-12-31')-1 else NULL end [Last Time Additional Visit]
      ,case when [Visit Cancelled] <> '' then DATEADD(day, CONVERT(int, [Visit Cancelled]), '1899-12-31')-1 else NULL end [Visit Cancelled]
      ,[Action cancelled]
      ,[ContactSalesforceId]
  INTO SalesforceReporting..Backlog_HS_Overdue_ThirtyDays
  FROM [SalesforceReporting].[dbo].[HS_OVERDUE_THIRTY]